name = "CSVFiles"
uuid = "5d742f6a-9f54-50ce-8119-2520741973ca"
version = "1.0.0-DEV"

[deps]
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
DataValues = "e7dc6d0d-1eca-5fa6-8ad6-5aecde8b7ea5"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
IterableTables = "1c8ee90f-4401-5389-894e-7a04a3dc0f4d"
IteratorInterfaceExtensions = "82899510-4779-5014-852e-03e436cf321d"
TableShowUtils = "5e66a065-1f0a-5976-b372-e0b8c017ca10"
TableTraits = "3783bdb8-4a98-5b6b-af9a-565f29a5fe9c"
TableTraitsUtils = "382cd787-c1b6-5bf2-a167-d5b971a19bda"
TextParse = "e0df1984-e451-5cb5-8b61-797a481e67e3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
CodecZlib = "≥ 0.5.2"
DataValues = "≥ 0.4.4"
FileIO = "≥ 1.0.1"
HTTP = "≥ 0.6.14"
IterableTables = "≥ 0.8.3"
IteratorInterfaceExtensions = "^0.1.1, ^1"
TableShowUtils = "≥ 0.1.1"
TableTraits = "^0.4, ^1"
TableTraitsUtils = "0.2.1, 0.3, 0.4, 1"
TextParse = "≥ 0.7.0"
julia = "1"
